server.port: 7002
server.error.include-message: always

logging:
  level:
    root: INFO
    se.magnus: DEBUG

spring:
  data:
    mongodb:
      host: localhost
      port: 27107
      database: recommendation-db

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb

server:
  port: 8080
